name: gym_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: PlusJakartaSans
      fonts:
          # font weight adjusted with fontVariations and the 'wght' (200-800 range) axis
        - asset: assets/fonts/PlusJakartaSans-Variable.ttf
        - asset: assets/fonts/PlusJakartaSans-Italic-Variable.ttf
          style: italic

    - family: Fraunces
      fonts:
          # font weight, wonky adjusted with fontVariation
        - asset: assets/fonts/Fraunces-Variable.ttf
